version: "3.8"

services:
  nginx:
    build: ./nginx/
    container_name: nginx
    ports:
      - 7777:80
    volumes:
      - ./docker-volume/log/:/var/log/nginx/

  php:
    build: ./php/
    container_name: php
    expose:
      - 9000
    volumes:
      - ./docker-volume/html/:/var/www/html/

  mysql:
    image: mysql:8.0.28
    container_name: mysql
    volumes:
      - ./docker-volume/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
